---
    - name: Wait for APT lock to be released
      shell: >
        while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
          sleep 1
        done
      become: yes
      become_method: sudo
      become_flags: "-S"

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: Update APT package cache after adding Docker repository
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
