---
- name: Update System
  yum:
    name: "*"
    state: latest
- name: supprimer toutes les versions précédentes 
   yum:
     name: yum-utils
     state: absent
- name: Install pip for Python 3
  raw: test -e /usr/bin/python3 || (yum -y install python3 && alternatives --set python /usr/bin/python3)
  args:
    executable: /bin/bash
  become: yes

- name: Install Docker Python library
  yum:
    name: docker
    state: present

- name: Gathering Facts
  setup:

- name: Install pre-requisite packages
  yum:
    name: "{{ item }}"
    state: present
    lock_timeout: 180
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python3
    - python3-pip

- name: Download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
    dest: /tmp/get-pip.py

- name: Install python-pip
  command: python3 /tmp/get-pip.py
  ignore_errors: yes

- name: Install Docker python module
  pip:
    name: docker
    executable: /usr/local/bin/pip3

- name: Update urllib3
  pip:
    name: urllib3[secure]
    executable: /usr/local/bin/pip3

- name: Display Python and Pip versions
  command: "{{ item }}"
  with_items:
    - python3 --version
    - /usr/local/bin/pip3 --version

- name: Add remote user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Add Docker ce repo
  copy:
    content: |
      [docker-ce]
      name=Amazon Linux Extras docker
      baseurl=https://amazonlinux.${region}.amazonaws.com/2/docker-ce/stable/$basearch
      gpgcheck=0
      enabled=1
      skip_if_unavailable=True
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "Amazon"
  vars:
    region: us-east-1

- name: "Install Docker on Amazon Linux"
  command: amazon-linux-extras install docker -y
  args:
    creates: /usr/bin/docker
  when: ansible_distribution == "Amazon"

- name: Start and enable the Docker daemon
  service: 
    name: docker 
    state: started 
    enabled: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
