
// Pipeline infrastructure Cluster K8S Production

pipeline {
    agent any
    environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins-aws-access-key-id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins-aws-secret-access-key')
            }

    stages { 

    
        stage ('Provision EKS- Terraform init') {
            steps {  
                echo 'initialisation de Terraform' 
                script {
                    dir ('terraform-manifest-files-eks') {
                        sh "terraform init"
                    }
                }
            }  
        }
        stage ('Provision eks- Terraform plan') {
            steps {  
                echo 'terraform plan' 
                script {
                    dir ('terraform-manifest-files-eks') {
                        sh "terraform plan"
                    }
                }
            }  
        }
        stage ('Provision eks- Terraform apply') {
            steps {  
                when { branch 'master'}
                echo 'appliquer le code Terraform' 
                script {
                    dir ('terraform-manifest-files-eks') {
                        sh "terraform apply -auto-approve"
                    }
                }
            }  
        }
        stage ('Update kube-config') {
            steps {  
                echo 'mise à jour vers eks kubeconfig' 
                script {
                    dir ('terraform-manifest-files-eks') {
                        sh "aws eks update-kubeconfig --name DC_Server-Cluster-K8S-Prod"
                    }
                }
            }  
        }
    }
}

